baseURL: https://eens-it.netlify.app
title: "Extra Ecclesiam Nulla Salus"

module:
   imports:
      - path: github.com/eens1/config

languageName: "Italiano"
defaultContentLanguage: it
params:
   dateFormat: "Jan 02, 2006"
menu:
   main:
      - name: Home
        url: /
        weight: 1

      - name: "English"
        url: "https://eens-en.netlify.app"
        weight: 2 

      - name: "Fran√ßais"
        url: "https://eens-fr.netlify.app"
        weight: 3 
